version: 0.0
os: linux
files:
  - source: /
    destination: /app
permissions:
  - object: /app/
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: meonzi
      timeout: 60
      runas: ec2-user
