version: "3.8"

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  localstack:
    image: localstack/localstack
    ports:
      - 4572:4572
      - 4566:4566
    environment:
      - SERVICES=s3,sns
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d
