version: "3.8"

services:
  traefik:
    image: traefik
    restart: always
    labels:
      - "traefik.http.routers.traefik.rule=Host(`api.localhost`)"                  # rule for route to traefik ex) api.example.com
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"              # load balance to port 8080 when traefik requested

    command:           
      - --entrypoints.web.address=:80                                              # http entry point
      - --providers.docker                                                         # enable docker provider
      - --api.insecure                                                             # enable insecure dashboard

    ports: 
      - "80:80"                                                                    # http port forwarding
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  meonzi:
    build: .
    restart: always
    labels: 
      - "traefik.http.routers.meonzi.rule=Host(`localhost`)"                       # host routing rule from external
      - "traefik.http.services.meonzi.loadbalancer.server.port=5000"               # load balance to port 5000 when meonzi requested
    environment: 
      - DATABASE_HOST=database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  localstack:
    image: localstack/localstack
    ports:
      - 4572:4572
      - 4566:4566
    environment:
      - SERVICES=s3,sns
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d
