// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	app2 "github/four-servings/meonzi/account/app"
	"github/four-servings/meonzi/account/infra"
	"github/four-servings/meonzi/account/interfaces"
	"github/four-servings/meonzi/app"
	"github/four-servings/meonzi/di"
	"time"
)

// Injectors from wire.go:

func GetApp() *app.App {
	dbConn := app.GetDBConn()
	client := di.ProviderDatabase(dbConn)
	echo := di.ProviderEcho()
	accountClient := di.ProviderAccountTable(client)
	accountRepository := infra.NewAccountRepository(accountClient)
	googleAdapter := infra.NewGoogleAdapter()
	kakaoAdapter := infra.NewKakaoAdapter()
	socialService := infra.NewSocialService(googleAdapter, kakaoAdapter)
	duration := _wireDurationValue
	commandBus := app2.NewCommandBus(accountRepository, socialService, duration)
	validate := di.ProviderValidator()
	authService := infra.NewAuthService()
	controller := interfaces.NewAccountController(commandBus, validate, authService)
	routing := infra.NewRoute(echo, controller)
	setRoute := app.Routing(routing)
	appApp := app.NewApp(client, echo, setRoute)
	return appApp
}

var (
	_wireDurationValue = time.Second *
		3
)
