// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github/four-servings/meonzi/account/domain"
	"github/four-servings/meonzi/account/infra"
	"github/four-servings/meonzi/config"
	"github/four-servings/meonzi/di"
)

// Injectors from wire.go:

func exampleGetAccountRepository() domain.AccountRepository {
	dbConn := config.GetDBConn()
	client := di.ProviderDatabase(dbConn)
	accountClient := di.ProviderAccountTable(client)
	accountRepository := infra.NewAccountRepository(accountClient)
	return accountRepository
}
