// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "social_type", Type: field.TypeUint8},
		{Name: "social_id", Type: field.TypeString, Size: 30},
		{Name: "name", Type: field.TypeString, Size: 30},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "update_at", Type: field.TypeTime},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:        "account",
		Columns:     AccountColumns,
		PrimaryKey:  []*schema.Column{AccountColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "account_social_type_social_id",
				Unique:  true,
				Columns: []*schema.Column{AccountColumns[1], AccountColumns[2]},
			},
			{
				Name:    "account_delete_at",
				Unique:  false,
				Columns: []*schema.Column{AccountColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
}
