name: deploy workflows
on: 
  push:
    branches:
      - master
jobs:
  test:
    name: Run test
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./... -count=1
  deploy:
    name: Build application
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o meonzi
    - name: Compress build output
      run: zpi -qq -r ./$GITHUB_SHA.zip .
    - name: Config AWS credentials
      use: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $
        aws-secret-access-key: $
        aws-region: $
    - name: Upload bundle
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://meonzi-code-deploy/$GITHUB_SHA.zip
    - name: Deploy code
      run: aws deploy create-deployment --application-name meonzi --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name production --s3-location bucket=meonzi-code-deploy,bundleType=zip,key=$GITHUB_SHA.zip
