name: deploy workflows
on: 
  push:
    branches:
      - master
jobs:
  test:
    name: Run test
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./... -count=1
  build:
    name: Build application
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o meonzi
